config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks
  end
  root 'projects#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  resources :tasks, only: [:index]

  # resources :wiki, controller: 'wiki'
  get 'wiki', to: 'wiki#main', as: :main_wiki
  resources :wiki, controller: 'wiki'

  get 'dashboard', to: 'dashboard#index', as: :dashboard

  get 'profile', to: 'profile#show'
  get 'profile/edit', to: 'profile#edit', as: :edit_profile
  patch 'profile', to: 'profile#update'
end

app/models/task.rb
# frozen_string_literal: true

require 'acts-as-taggable-on'
class Task < ApplicationRecord
  # include Taggable
  belongs_to :project
  belongs_to :user
  has_rich_text :description
  scope :completed, -> { where(status: 'completed') }
  acts_as_taggable_on :tags

  after_save :update_project_progress
  after_destroy :update_project_progress

  private

  def update_project_progress
    project.save
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build(task_params)
    @task.user = current_user || User.first
    if @task.save
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # Other actions...

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :status, :user_id)
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @task]) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", project_task_path(@task.project, @task)%> |
  <%= link_to "Back to tasks", project_task_path(@task.project, @task) %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
   <p>
      <%= link_to "Show this task", project_task_path(task.project, task) %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_project_task_path(@project) %>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h2 class="mb-0">New Task</h2>
        </div>
        <div class="card-body">
          <%= form_with(model: [@project, @task]) do |form|  %>
            <% if @task.errors.any? %>
              <div class="alert alert-danger">
                <h3><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h3>
                <ul>
                  <% task.errors.full_messages.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="mb-3">
              <%= form.label :title, class: 'form-label' %>
              <%= form.text_field :title, class: 'form-control', required: true %>
              <div class="invalid-feedback">Title is required.</div>
            </div>

            <div class="mb-3">
              <%= form.label :description, class: 'form-label' %>
              <%= form.text_area :description, class: 'form-control rows:4' %>
              <%# replace text area with rich_text_area :description, class: 'trix-content' %>
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <%= form.label :due_date, class: 'form-label' %>
                <%= form.date_field :due_date, class: 'form-control' %>
              </div>
              <div class="col-md-6 mb-3">
                <%= form.label :status, class: 'form-label' %>
                <%= form.text_field :status, class: 'form-control' %>
              </div>

              <div>
                <%= form.label :project_id, style: "display: block" %>
                <%= form.text_field :project_id, class: 'form-control' %>
              </div>
            </div>

            <div class="d-grid gap-2">
              <%= form.submit 'Create Task', class: 'btn btn-primary btn-lg' %>
            </div>
          <% end %>
        </div>
      </div>
        <%= render "tasks/shared/tag" %>
      <div class="mt-3">
        <%# <%= link_to 'Back to tasks', projects_tasks_path, class: 'btn btn-outline-secondary' %> %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'tasks/shared/tag' %> 
<div>
  <%= link_to "Edit this task", edit_project_task_path(@task.project, @task) %> |
  <%= link_to "Back to tasks", project_tasks_path(@task.project) %>

  <%= button_to "Destroy this task", project_task_path(@task.project, @task), method: :delete %>
</div>