config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks
  end
  root 'projects#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  resources :tasks, only: [:index]

  # resources :wiki, controller: 'wiki'
  get 'wiki', to: 'wiki#main', as: :main_wiki
  resources :wiki, controller: 'wiki'

  get 'dashboard', to: 'dashboard#index', as: :dashboard

  get 'profile', to: 'profile#show'
  get 'profile/edit', to: 'profile#edit', as: :edit_profile
  patch 'profile', to: 'profile#update'
end

app/views/shared/_sidebar.html.erb
<nav id="sidebar" class="sidebar col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="sidebar-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to dashboard_path, class: "nav-link #{active_class('dashboard')}" do %>
            <i class="bi bi-speedometer2"></i> Dashboard
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to profile_path, class: "nav-link #{active_class('profile')}" do %>
          <i class="bi bi-person"></i> Profile
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to projects_path, class: "nav-link #{active_class('projects')}" do %>
          <i class="bi bi-folder"></i> Projects
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to tasks_path, class: "nav-link #{active_class('tasks')}" do %>
          <i class="bi bi-list-task"></i> Tasks
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to wiki_index_path, class: "nav-link #{active_class('wiki')}" do %>
          <i class="bi bi-book"></i> Wiki
        <% end %>
      </li>
    </ul>
  </div>
</nav>